dubbo:
  application:
    name: dubbo-client
    owner: neo
  registry:
    address: zookeeper://122.51.167.43:2181
    check: true
    group: dubbo-test
    simplified: true
  metadata-report:
    address: zookeeper://122.51.167.43:2181
    retry-times: 30
    cycle-report: false
    group: dubbo-test
  scan:
    base-packages: com.zookeeper


---
server:
  port: 6110
